// hey there, kindly read this file till the end for better configuration

global.settings = {
  OWNER_NUMBERS: "2348119081041", // your number with country code
  OWNER_NAME: 'Master Temmy', // your owner name 
  BOT_NAME: "KORD", // your preferred bot name
  SESSION_ID: 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSU94bEtBTW1MZEVsRzZ3Z1ZESWd5alFyZG5YbjZsd3ZyY2lCYTV3cFlGYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibmtxNnIvRTZ4OUhGVzk5ZHRvUkY3K2RiSmxFQTFIRjkyWGtkWmIwUm8wZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJrTEw4NGNvSkYzZnRjcExIekFpclFPTHBhZkdTeW50RmU3OTIwcFg2akhNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJlaVAvUXFZWW5hSlVQbEp5aW81RnZMUVUvYmNHdTdVZjlKK3pFQkhodmh3PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IllDN2wyYVNadVJrR2FCcnlLRVRZWWNjSlByc2ZaeVpDK1Z6VTQ3T0JEMGs9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im44VjVmMGgxNnJkd3J0UHlIbHRlNVJzWHM1cVdyNkRjWDZRb0hsYzZKekU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNE1lQ1VIck93Sy9KZ1l3c1FlSmdPVFZ3UHRiZmQ1S3EzRDlCbG5QQVRuYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiakVUWW4wM1Rtd0haTTNWZlEzVXBTR0x6WnQxLzNnY3BlOVdXOWlTamtTUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InFwNUZrQnhwRTdiR1dVSEs5YUJ0ZDlJNjZKaDQwL3ordXdHak85ZHQ2cDR2TnA0SmtQL1NjQllhTU1EM1o0NUMyWVA5WjNyQmNVSVJ2RkV6ck9TdkJBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjI5LCJhZHZTZWNyZXRLZXkiOiJCbzBlUzlHa1NDTEdTWUVtbm9ZaFc3K0c4WksyZERKQU95UmxPNXgwVEdFPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjIzNDgxMTkwODEwNDFAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNTdGQzg3OUM5MDQ1REVBREE1ODE5OTBBN0JBMDAxMUQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNzIwODYwNn1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MCwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiaXpEOW5nNzhTTVdpZXVCcnB2RFJvQSIsInBob25lSWQiOiIxMmE2YjBhNy1jMjkxLTQ2YTktODk1Ni03ZmIwZTRkZTA1NTgiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSEhMZWdpSkFUYXh4c0hVekt0S3hJYkp3ZHVJPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjNwM0dwaVlwTmtHWXJjNTJkUSs1WWcyc25KWT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJIMVhYTDFKOCIsIm1lIjp7ImlkIjoiMjM0ODExOTA4MTA0MToxMEBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTW1mM3BZQkVJem1ycndHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiVWUwQnNraHY5dmtONElGUm13bDRWV3pYMmVlcTVqT29rWG82MXBqdGxuZz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiUDd3VWtrK2ZUc05NdTVFQnRJdGpLbXd2Q2hvQXp5cmFsWnUyUHZRL3JrdHBodlJ1MUhIM3Uyb1o4aVFxUTA0TTI3a2g5K0JNRkk0QVBBLzhtNVVRQWc9PSIsImRldmljZVNpZ25hdHVyZSI6ImN2d0FKWVA2TjhXUFY0Y3JLd0NNUGlrNzJLbWVSbzQrMzQzdyt0NnpUbDR0QkVTOVpOeHpkWHBsakdobGlYdmRnakVmZ1VqZm9Rck5STlZCWU5NeEJ3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0ODExOTA4MTA0MToxMEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJWSHRBYkpJYi9iNURlQ0JVWnNKZUZWczE5bm5xdVl6cUpGNk90YVk3Wlo0In19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzM3MjA4NjAxLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUhmUiJ9', // replace your_sessionid with yours and make sure its inside rhe quotes
  INVINCIBLE_MODE: false, // toogle invincible mode 
  WORK_MODE: "Public",
  TIME_ZONE: "Africa/Lagos",
  ANTI_VIEWONCE: true,
  READ_ALL_MESSAGES: false,
  AUTO_READ_STATUS: true,
  PREFIX: [".", "/", "!"],
  GROUP_EVENTS: true,
  WELCOME_MESSAGE: "Hello! I'm KORD-AI, your friendly WhatsApp bot.",
  DEFAULT_TRANSLATION_LANG: "en",
  COMMAND_COOLDOWN_TIME_IN_MS: 0.01,
  MAX_COMMANDS_PER_MINUTE: 100,
  MAX_DOWNLOAD_SIZE: 100,
  AUTO_LIKE_STATUS: true,
  AUTO_LIKE_EMOJI: '🌻',
  BANKING_DETAILS: {
    bank: "Kord-Ai Bank", // the name of your preferred bank
    acc_number: "1234567890", // account number for your preferred bank
    acc_name: "MyAccountName" // name of your bank
  },
  /* You can also replace the numbers with your addresses if you're using crypto, a command for this will come soon. */
  API_KEYS: {
    OPENWEATHERMAP_API_KEY: ''
  },
  isHackEnable: true,
  SAFE_SEARCH: true,
  REJECT_CALLS: true,
  SEND_WELCOME_MESSAGE: false,
  WELCOME_MESSAGE: "👋 Welcome to the group! We're glad to have you here. 😊",
  DELETE_WA_LINKS: false,
  BAD_WORD_FILTER: true,
  BAD_WORDS: ['badword1', 'badword2', 'fuck', 'bitch', 'hentai'],
  ANTI_DELETE_ENABLED: true,
};
